# Generated by Django 4.2.7 on 2023-12-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='userID',
            new_name='userId',
        ),
    ]
