# Generated by Django 4.2.7 on 2023-12-04 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('participants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.manager')),
            ],
        ),
    ]
