# Generated by Django 4.2.7 on 2023-12-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_fight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fight',
            name='participants',
        ),
    ]
