# Generated by Django 4.2.7 on 2023-12-04 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_fighter_fight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='manager',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, to='backend.manager'),
        ),
    ]
