# Generated by Django 4.2.7 on 2023-12-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_fighter_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='name',
        ),
    ]
