# Generated by Django 4.2.7 on 2023-12-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_manager_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='name',
            field=models.CharField(default='DIDNT HAVE ANY ISSUES WITH THIS INITALLY WTF', max_length=200),
        ),
    ]
