# Generated by Django 4.2.7 on 2023-12-04 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_manager_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='fight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.fight'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.manager'),
        ),
    ]
