# Generated by Django 4.2.7 on 2023-12-04 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_fighter_fight_alter_fighter_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.manager'),
        ),
    ]
