# Generated by Django 4.2.7 on 2023-12-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_fighter_fight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='fight',
        ),
        migrations.AlterField(
            model_name='fighter',
            name='manager',
            field=models.CharField(max_length=200),
        ),
    ]
