# Generated by Django 4.2.7 on 2023-12-04 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_fighter_fight_alter_fighter_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='fight',
            field=models.ForeignKey(blank=True, default=-1, on_delete=django.db.models.deletion.CASCADE, to='backend.fight'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='manager',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='backend.manager'),
        ),
    ]
